# Generated by Django 3.2.9 on 2021-12-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0007_auto_20210307_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle1',
            fields=[
                ('Vehicle_license_plate', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Vehicle_name', models.CharField(max_length=60)),
                ('Vehicle_company', models.CharField(max_length=60)),
                ('Vehicle_model', models.CharField(max_length=60)),
                ('Vehicle_type', models.CharField(max_length=20)),
                ('Vehicle_No_of_Seats', models.IntegerField()),
                ('Vehicle_fuel', models.CharField(max_length=10)),
                ('Vehicle_price', models.IntegerField()),
                ('Vehicle_pickup_date', models.DateField()),
                ('Vehicle_release_date', models.DateField()),
                ('Vehicle_description', models.CharField(max_length=1500)),
                ('Vehicle_image1', models.ImageField(upload_to='img/Vehicle_images/')),
                ('Vehicle_image2', models.ImageField(upload_to='img/Vehicle_images/')),
                ('Vehicle_image3', models.ImageField(upload_to='img/Vehicle_images/')),
            ],
        ),
    ]
