# Generated by Django 3.2.9 on 2021-12-11 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0010_auto_20211212_0107'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehicle1',
        ),
    ]
