# Generated by Django 3.2.9 on 2021-11-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerHome', '0005_auto_20210129_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.CharField(max_length=100)),
                ('customer_password', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
            ],
        ),
    ]
