# Generated by Django 3.2.9 on 2021-11-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerHome', '0006_customers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='id',
        ),
        migrations.AlterField(
            model_name='customers',
            name='customer_email',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
